export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const DELETE_MOVIE = "DELETE_MOVIE";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILED = "DELETE_MOVIE_FAILED";

export const EDIT_MOVIE = "EDIT_MOVIE";
export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_FAILED = "EDIT_MOVIE_FAILED";

export const ADD_MOVIE = "ADD_MOVIE";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILED = "ADD_MOVIE_FAILED";

export const TICKET = "TICKET";
export const TICKET_SUCCESS = "TICKET_SUCCESS";
export const TICKET_FAILED = "TICKET_FAILED";

export const DELETE_TICKET = "DELETE_TICKET";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAILED = "DELETE_TICKET_FAILED";

export const SHOW_MOVIE = "SHOW_MOVIE";
export const SHOW_MOVIE_SUCCESS = "SHOW_MOVIE_SUCCESS";
export const SHOW_MOVIE_FAILED = "SHOW_MOVIE_FAILED";