export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const ACCOUNT = "ACCOUNT";
export const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS";
export const ACCOUNT_FAILED = "ACCOUNT_FAILED";

export const ACCOUNT_INFORMATION = "ACCOUNT_INFORMATION";
