export const PROMOTION_REQUEST = 'PROMOTION_REQUEST'
export const PROMOTION_SUCCESS = 'PROMOTION_SUCCESS'
export const PROMOTION_FAILED = 'PROMOTION_FAILED'

export const DETAIL_PROMOTION = 'DETAIL_PROMOTION'
