export const ADD_TICKET_REQUEST = "ADD_TICKET_REQUEST";
export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS";
export const ADD_TICKET_FAILED = "ADD_TICKET_FAILED";

export const EDIT_SEAT_REQUEST = "EDIT_SEAT_REQUEST";
export const EDIT_SEAT_SUCCESS = "EDIT_SEAT_SUCCESS";
export const EDIT_SEAT_FAILED = "EDIT_SEAT_FAILED";
